### ISSUE TITLE
AllToMp3 not downloading songs

### ISSUE THREAD

**Issue by nicolasatalianis** [AllToMP3/alltomp3-app#144]
Windows 10 
Operating normally, good internet connection as well as memory but downloads dont start to download. 
![image](https://user-images.githubusercontent.com/60035349/72663776-e5512c00-39fe-11ea-951d-5bd1a9f80772.png)

its been 45 min and still no progress

**Comment by Cristobal65** [comment]
MacOs Sierra
AllTOMp3 Version 3:11
Same here:
![Captura de pantalla 2020-01-19 a las 10 58 34](https://user-images.githubusercontent.com/51745634/72678935-c7d99c00-3aaa-11ea-9f7e-1643d5adfb39.png)

**Comment by tojwek123** [comment]
For youtube download a temporary solution might be updating 'youtube-dl' binary. Check my other comment: https://github.com/AllToMP3/alltomp3-app/issues/142#issuecomment-576027297

**Comment by Cristobal65** [comment]
Works to me fine. Thank You.
For general Information. i've downloaded https://yt-dl.org/downloads/2020.01.15/youtube-dl-2020.01.15.tar.gz
Then, extract files, but, instead copy/replace de file located in bin folder, i copy replace the main one located on the youtube-dl root folder to "...\AppData\Local\Programs\AllToMP3\resources\app.asar.unpacked\node_modules\youtube-dl\bin".

**Comment by MinChoco3007** [comment]
![Annotation 2020-01-19 215816](https://user-images.githubusercontent.com/58868309/72695540-e2416300-3b06-11ea-802e-5c27e69bad24.png)
same here... from spotify

**Comment by tuanminh26596** [comment]
> Works to me fine. Thank You.
> For general Information. i've downloaded https://yt-dl.org/downloads/2020.01.15/youtube-dl-2020.01.15.tar.gz
> Then, extract files, but, instead copy/replace de file located in bin folder, i copy replace the main one located on the youtube-dl root folder to "...\AppData\Local\Programs\AllToMP3\resources\app.asar.unpacked\node_modules\youtube-dl\bin".

IT'S WORK !! THANKS

**Comment by NTag** [comment]
I released a new version 0.3.12 which should fix this problem.

**Comment by PrepareForMayhem** [comment]
> I released a new version 0.3.12 which should fix this problem.

Still doesnt work.
@NTag

**Comment by dfilipovic39** [comment]
Hey, try to remove application data. its under /.config/AllToMP3 on linux system, guess \AppData\Local\Programs/AllToMP3 on windows and then reistall

**Comment by Sharks67** [comment]
version 3.12 still causing same problem - nil download. this has been "running"all day
![AllToMP3](https://user-images.githubusercontent.com/62013223/76302850-1f8dca00-62da-11ea-983e-1abc9eebd84a.jpg)

**Comment by Luigi90839** [comment]
Yeah it's not working the new version 0.3.12

**Comment by Luigi90839** [comment]
![Captura de pantalla (87)](https://user-images.githubusercontent.com/62360730/77014592-48483c00-6938-11ea-8cc3-28cc711c9de0.png)

**Comment by nicolasatalianis** [comment]
it happened again. not working again. :(

**Comment by Loly81** [comment]
Hi, I got AllToMp3 yesterday and it was working great until I turned off my laptop and a few hours later wasn't working anymore.

**Comment by PlushBanshee** [comment]
same here and i replaced the youtube-dl thing :(

**Comment by Loly81** [comment]
I found that it's easier to convert one album at a time than an entire
playlist with hundreds of songs. Also, the systems goes down for a few
days, but works back again. I suggest you get a ready what you want to
convert for when it works and do approximately what an album would be at a
time. Don't close the program if it's working, just keep converting to take
advantage of the time being.

**Comment by GreenishClovers** [comment]
I can relate to all comments... I see the new version was announced in Jan of this year... Is there a new version since then? Or a resolved solution?

**Comment by NTag** [comment]
I released an update. However it only supports YouTube URLs, Spotify/Deezer/song title searches are broken for now, sorry.

**Comment by Luigi90839** [comment]
That's bullshit, it can't even download the songs from YouTube URLs fix it!

**Comment by achhid** [comment]
after viewing what the whole people are talking about here, i found a solution for windows (at least for YouTube videos). Download latest version of FFmpeg (ffmpeg-release-full.7z from gyan.dev ) and replace files in AllToMP3\resources\app.asar.unpacked\bin (ffmpeg.exe and ffprobe.exe) after that download should work

**Comment by jpsymmons33** [comment]
Hi my alltomp3 is Still Not Working. Can you please send a latest update if possible it's not downloading anything. Please Fix This Problem. 
Many Thanks 
Jordan Symmons

**Comment by JPaul23** [comment]
> I released an update. However it only supports YouTube URLs, Spotify/Deezer/song title searches are broken for now, sorry.

Even though it might not work, you did a great job developing that software. It helped in the past.
Thank you!!

**Comment by jpsymmons33** [comment]
Can you please fix the Song title searches.

Many thanks

Jordan Symmons

**Comment by SnakeSabil** [comment]
![image](https://user-images.githubusercontent.com/81631059/120148908-bf4eb500-c20a-11eb-9c9d-e8304086625a.png)
I left it for half an hour and still no progress... Help, please..!

**Comment by GreenishClovers** [comment]
> ![image](https://user-images.githubusercontent.com/81631059/120148908-bf4eb500-c20a-11eb-9c9d-e8304086625a.png)
> I left it for half an hour and still no progress... Help, please..!

I use YouTube for songs... I dont bother with other options.... 👍🏼

**Comment by nisro-source** [comment]
It doesn't work for me either, I hope someone solves the problem would do me a favor thanks.

**Comment by jpsymmons33** [comment]
Mine doesn't work either  wish it did.
